name: ah
networks:
  network:
services:
  docs:
    extends:
      file: ../../services/app/docker-compose.yaml
      service: app
    labels:
      - "traefik.http.routers.docs.entrypoints=web"
      - "traefik.http.routers.docs.rule=Host(`docs.amarhazem.localtest.me`)"
      - "traefik.http.services.docs.loadbalancer.server.port=3000"
  traefik:
    extends:
      file: ../../services/traefik/docker-compose.yaml
      service: traefik
