services:
  mailhog:
    image: mailhog/mailhog:${MAILHOG_VERSION:-v1.0.1}
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8025",
        ]
      timeout: 20s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.amarhazem.localtest.me`)"
      - "traefik.http.routers.mailhog.entrypoints=web"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    networks:
      - network
    restart: unless-stopped
