services:
  traefik:
    command:
      - '--api.dashboard=true'
      - '--api.insecure=false'
      - '--entrypoints.web.address=:80'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    image: traefik:${TRAEFIK_VERSION:-v3.3}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.amarhazem.localtest.me`)'
      - 'traefik.http.routers.traefik.entrypoints=web'
      - 'traefik.http.routers.traefik.service=api@internal'
    networks:
      - network
    ports:
      - '80:80'
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
