services:
  postgres:
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-portfolio}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      timeout: 5s
    image: postgres:${POSTGRES_VERSION:-17.4}
    networks:
      - network
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
