name: ah
networks:
  network:
services:
  pgadmin4:
    extends:
      file: ../../services/pgadmin4/docker-compose.yaml
      service: pgadmin4
  postgres:
    extends:
      file: ../../services/postgres/docker-compose.yaml
      service: postgres
  traefik:
    extends:
      file: ../../services/traefik/docker-compose.yaml
      service: traefik
volumes:
  pgadmin4:
  postgres:
